---
- name: Retrive the list of registeed systems with the same name
  uri:
    url: "{{ jumpcloud_api_v1_url }}/search/systems"
    method: POST
    headers:
      "Content-Type": "application/json"
      "Accept":       "application/json"
      "x-api-key":    "{{ jumpcloud_api_key }}"
    body_format:  json
    body: '{ "filter" :
    {"and" :
    [{ "displayName" : "{{ jumpcloud_displayName }}" },
    {"active" : "false" }]
    },
    "fields": "displayName _id" }'
    follow_redirects: all
    return_content: yes
    status_code: 200
  delegate_to: localhost
  register: jc_registered_systems_json_response
  when: jumpcloud_displayName is defined
  ignore_errors: yes

- debug:
    var: jc_registered_systems_json_response

- pause:
...
