---
- command:    grep -o -P '(?<=systemKey\":\")[a-zA-Z0-9]*' {{ jumpcloud_agent_config }}
  register:   jumpcloud_system_key_result
  become:     "{{ jumpcloud_use_sudo }}"
  changed_when: "not jumpcloud_system_key_result.stdout"

- set_fact:
    jumpcloud_system_key: "{{ jumpcloud_system_key_result.stdout }}"
...
