---
- name: Download JumpCloud Kickstart script
  get_url:
    url: "{{ jumpcloud_x_connect_url }}"
    dest: "{{ jumpcloud_kickstart_script }}"
    mode: 0755
    headers: "x-connect-key: {{ jumpcloud_x_connect_key }}"
  become: "{{ jumpcloud_use_sudo }}"

- name: Install JumpCloud Agent
  shell: "{{ jumpcloud_kickstart_script }}"
  args:
    creates: "{{ jumpcloud_agent_config}}"
  become: "{{ jumpcloud_use_sudo }}"

- name: Restart JumpCloud
  service:
    name:  "{{ jumpcloud_agent_service }}"
    state: restarted
  become: "{{ jumpcloud_use_sudo }}"

- name: Make Sure that jcagent.conf has been created
  wait_for:
    path: "{{ jumpcloud_agent_config}}"
    state: present
    timeout: 60
    msg: Timeout to find file "{{ jumpcloud_agent_config}}"


...
